### ISSUE TITLE
Rate limit issue.

### ISSUE THREAD

**Issue by pcartwright81** [barrald/strava-uploader#23]
I have a new api key with 100 requests every 15 minutes, 1000 daily.  I have successfully used the application to upload 20 gpx files every 20 minutes by changing the line counter >= 20.  For each file the request counter on the website goes up to an average of 4.5 requests per file.  I looked through the code and only see one request per file.  Any clue what is going on here?

**Comment by TimoKoole** [comment]
I am facing the same issue. I even had to lower the counter to 14. 
In the rest API the information looks to be there [strava docs](http://developers.strava.com/docs/rate-limits)
Looks like the python package does provide handling this nicely by providing:
[python docs](https://pythonhosted.org/stravalib/_modules/stravalib/client.html)
`   :param rate_limiter: A :class:stravalib.util.limiter.RateLimiter'object to use`
looks like the default rate limiter implementation is infact based on the old criteria
`        self.rules.append(XRateLimitRule(
            {'short': {'usageFieldIndex': 0, 'usage': 0,
                         # 60s * 15 = 15 min
                         'limit': 600, 'time': (60*15),
                         'lastExceeded': None},
             'long': {'usageFieldIndex': 1, 'usage': 0,
                        # 60s * 60m * 24 = 1 day
                        'limit': 30000, 'time': (60*60*24),
                        'lastExceeded': None}}))
`

So I guess creating a rate limiter that has the correct rates would fix all of this. specially since it looks to have a flag that will auto pause for you.. `raise_exc`

maybe ill give it a shot
